name: Various checks

on: [push]

jobs:
  image-optimizer:
    name: Run image optimizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.6.1